apiVersion: apps/v1
kind: Deployment
metadata:
  name: statsd-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statsd-exporter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: statsd-exporter
    spec:
      containers:
      - name: statsd-exporter
        image: prom/statsd-exporter
        args: ["--statsd.mapping-config=/etc/statsd-exporter/statsd-mapping.conf"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/statsd-exporter
        ports:
        - name: statsd
          containerPort: 9125
          protocol: UDP
        - name: metrics
          containerPort: 9102
      volumes:
      - name: config-volume
        configMap:
          name: statsd-exporter-config
