apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: result
  name: result
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: result
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: result
    spec:
      automountServiceAccountToken: true
      containers:
      - image: dockersamples/examplevotingapp_result@sha256:1e805ccebf14b5317a5e3bbea571aa5494ced8eca8a77ebd12af9f9b62d59eb2
        imagePullPolicy: IfNotPresent
        name: result
        ports:
        - containerPort: 80
          name: result
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
